version: '2'
services:
    php:
        build : ./docker/php
        volumes:
            - .:/var/www/html
            - ./docker/php/config:/usr/local/etc/php/conf.d
            - ~/.composer:/root/.composer
        links:
            - rabbitmq
        working_dir: /var/www/html
    rabbitmq:
        image: rabbitmq:management
        ports:
            - "5672:5672"
            - "8080:15672"
        environment:
            RABBITMQ_DEFAULT_USER: "rabbitmq"
            RABBITMQ_DEFAULT_PASS: "rabbitmq"
            RABBITMQ_DEFAULT_VHOST: "/"
